<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0" xmlns:ns1="http://purl.org/dc/terms/" xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <start>
    <choice>
      <ref name="resource"/>
      <ref name="collection"/>
    </choice>
  </start>
  <define name="identifier-and-path">
    <attribute name="identifier">
      <a:documentation>Identifier of the Collection or Resource</a:documentation>
      <data type="anyURI"/>
    </attribute>
    <optional>
      <attribute name="path">
        <a:documentation>Path to the relevant Collection or Resource</a:documentation>
        <data type="anyURI"/>
      </attribute>
    </optional>
  </define>
  <define name="parent">
    <optional>
      <element name="parent">
        <a:documentation xml:lang="eng">Identifier of the parent if required by a parent
                  collection</a:documentation>
        <data type="anyURI"/>
      </element>
    </optional>
  </define>
  <define name="baseDetails">
    <element name="title">
      <a:documentation>Title / name of a Collection or Resource</a:documentation>
      <data type="string"/>
    </element>
    <optional>
      <element name="description">
        <a:documentation>Description of a Collection or Resource</a:documentation>
        <data type="string"/>
      </element>
    </optional>
  </define>
  <define name="dublinCore">
    <element name="dublinCore">
      <zeroOrMore>
        <element>
          <a:documentation>Something</a:documentation>
          <choice>
            <name>ns1:abstract</name>
            <name>ns1:accessRights</name>
            <name>ns1:accrualMethod</name>
            <name>ns1:accrualPeriodicity</name>
            <name>ns1:accrualPolicy</name>
            <name>ns1:alternative</name>
            <name>ns1:audience</name>
            <name>ns1:available</name>
            <name>ns1:bibliographicCitation</name>
            <name>ns1:conformsTo</name>
            <name>ns1:contributor</name>
            <name>ns1:coverage</name>
            <name>ns1:created</name>
            <name>ns1:creator</name>
            <name>ns1:date</name>
            <name>ns1:dateAccepted</name>
            <name>ns1:dateCopyrighted</name>
            <name>ns1:dateSubmitted</name>
            <name>ns1:description</name>
            <name>ns1:educationLevel</name>
            <name>ns1:extent</name>
            <name>ns1:format</name>
            <name>ns1:hasFormat</name>
            <name>ns1:hasPart</name>
            <name>ns1:hasVersion</name>
            <name>ns1:identifier</name>
            <name>ns1:instructionalMethod</name>
            <name>ns1:isFormatOf</name>
            <name>ns1:isPartOf</name>
            <name>ns1:isReferencedBy</name>
            <name>ns1:isReplacedBy</name>
            <name>ns1:isRequiredBy</name>
            <name>ns1:issued</name>
            <name>ns1:isVersionOf</name>
            <name>ns1:language</name>
            <name>ns1:license</name>
            <name>ns1:mediator</name>
            <name>ns1:medium</name>
            <name>ns1:modified</name>
            <name>ns1:provenance</name>
            <name>ns1:publisher</name>
            <name>ns1:references</name>
            <name>ns1:relation</name>
            <name>ns1:replaces</name>
            <name>ns1:requires</name>
            <name>ns1:rights</name>
            <name>ns1:rightsHolder</name>
            <name>ns1:source</name>
            <name>ns1:spatial</name>
            <name>ns1:subject</name>
            <name>ns1:tableOfContents</name>
            <name>ns1:temporal</name>
            <name>ns1:title</name>
            <name>ns1:type</name>
            <name>ns1:valid</name>
          </choice>
          <optional>
            <attribute name="xml:lang">
              <data type="language"/>
            </attribute>
          </optional>
          <data type="string"/>
        </element>
      </zeroOrMore>
    </element>
  </define>
  <define name="extension">
    <element name="extensions">
      <a:documentation>Structured metadata contains any other optional metadata that are not part of
                DublinCore Terms namespace</a:documentation>
      <zeroOrMore>
        <element>
          <anyName>
            <except>
              <nsName ns="http://purl.org/dc/terms/"/>
            </except>
          </anyName>
          <optional>
            <attribute name="xml:lang">
              <data type="language"/>
            </attribute>
          </optional>
          <text/>
        </element>
      </zeroOrMore>
    </element>
  </define>
  <define name="members">
    <a:documentation>Children member of a collection or ressource</a:documentation>
    <element name="members">
      <oneOrMore>
        <choice>
          <ref name="collection"/>
          <ref name="resource"/>
          <element>
            <a:documentation>Relative link to a secondary collection file</a:documentation>
            <choice>
              <name>collection</name>
              <name>resource</name>
            </choice>
            <ref name="identifier-and-path"/>
          </element>
        </choice>
      </oneOrMore>
    </element>
  </define>
  <define name="mediatypeChild">
    <element name="mediatypeChild">
      <zeroOrMore>
        <element name="item">
          <attribute name="type">
            <data type="string"/>
          </attribute>
          <attribute name="href">
            <data type="anyURI"/>
          </attribute>
          <attribute name="mediatype">
            <data type="string"/>
          </attribute>
        </element>
      </zeroOrMore>
    </element>
  </define>
  <define name="collection-pattern">
    <ref name="identifier-and-path"/>
    <ref name="parent"/>
    <ref name="baseDetails"/>
    <optional>
      <ref name="mediatypeChild"/>
    </optional>
    <optional>
      <ref name="dublinCore"/>
    </optional>
    <optional>
      <ref name="extension"/>
    </optional>
    <optional>
      <ref name="members"/>
    </optional>
  </define>
  <define name="resource">
    <element name="resource">
      <ref name="collection-pattern"/>
    </element>
  </define>
  <define name="collection">
    <element name="collection">
      <ref name="collection-pattern"/>
    </element>
  </define>
</grammar>
